apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visitlog
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - secret.yaml
  - kustomization.yaml
