apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: visitlog
namespace: visitlog
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml