apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: visitlog
type: Opaque
stringData:
  POSTGRES_DB: visitlogdb
  POSTGRES_USER: visituser
  POSTGRES_PASSWORD: supersecret  # change this

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: visitlog
labels:
  app: postgres
spec:
  clusterIP: None  # Headless for StatefulSet DNS
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: visitlog
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi