apiVersion: v1
kind: Secret
metadata:
  name: visitlog-secret
  namespace: visitlog
  labels:
    app: visitlog
    environment: dev
    tier: backend
    managed-by: kustomize
    created-by: kustomize
    version: v1.0.0
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # base64 encoded value of "password"
  API_KEY: YXBpX2tleV9oZXJl  # base64 encoded value of "api_key_here"
  SECRET_KEY: c2VjcmV0X2tleV9oZXJl  # base64 encoded value of "secret_key_here"