name: terraform-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check

      # - name: Terraform Init
      #   working-directory: terraform
      #   run: terraform init -backend=false

      # - name: Terraform Validate
      #   working-directory: terraform
      #   run: terraform validate

  checkov:
    name: Checkov Scan - Terraform & Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkov - Terraform
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
      
      - name: Checkov - Kubernetes
        uses: bridgecrewio/checkov-action@master
        with:
          directory: clusters
          framework: kubernetes
  